services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - app-network

  web:
    container_name: web
    image: nginx:alpine  # Nginx image
    ports:
      - "9000:80"  # Host port 9000 dan container port 80 ga
    volumes:
      - ./:/var/www  # Laravel ilovasini qo'shish
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfiguratsiyasini qo'shish
    depends_on:
      - app  # PHP-FPM ishga tushishi uchun
    networks:
      - app-network  # Maxsus tarmoq

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
